### ISSUE TITLE
Beta release task list

### ISSUE THREAD

**Issue by hextraza** [BimberLab/DiscvrLabKeyModules#201]
- [x] Pagination must carry filters properly
- [x] Leading wildcard breaks string contains
- [x] in set OR has strange replacement behavior
- [x] Consistent and defined column order
- [x] Card should be the width of the table, use horizontal space
- [x] Verify variableSamples behavior, we're not seeing as many multivalued fields as we should
- [x] Ensure we're dealing with displaying multivalued fields appropriately
- [x] Hardcode contig = chromosome
- [x] Validate whether or not to restore the old search functionality
- [x] Second pass on the filter card to replace the existing filter button with a modal
- [x] Filter validation in handleSubmit
- [x] Validate we never reach the default case on the lucene operator switch, hardening should fix that
- [x] Consider forcing all columns to left-align? This is an issue with numeric columns when the width is wide
- [x] Consider whether we could have a max-width or flex-like property. The point is that some columns are inherently very narrow (like simple integers, REF/ALT, etc). Might be more natural to allow non-even col width
- [x] We should consider whether Genomic Position (and maybe others) can be completely hidden
- [x] Can the column header have a popup that shows the longer description of that column?
- [x] Filter dialog should use field label and not name (i.e. "Alt Allele" vs. "alt")
- [x] Discuss supporting an EQUALS_ONE_OF operator. 
- [x] Support DOES_NOT_EQUAL operator for strings
- [x] Support DOES_NOT_CONTAIN operator for strings
- [x] Verify offset works as expected
- [x] Fix display details widget, add View in Genome Browser button
- [x] SearchString=all bug
- [x] There should always be one filter in the search filter box, Remove Filter button should be removed if there's one
- [x] Integrate int+doublepoint queries to fix genomicPosition, start, end, etc
- [x] Discuss how the variableSamples field (as an example of long-string values) is rendered. Perhaps it could row-wrap, or have a hover function to see the full text?
- [x] The column definitions should be able to supply a list of allowable values (such as the IMPACT field). The filter dialog should render a select field instead of a free-text field. This ideally could also be a multi-select for the EQUALS_ONE_OF operator.
- [x] Discuss/improve handling of unexpected errors and app crashes. See ErrorBoundary, and figure out whether that's working as expected (which should provide an error page and I think report stacks to the server)
- [x] Ensure ref and alt match on the showDetailsWidget call for the feature
- [x] Fix some query operations
- [x] CADD_PH treated as string
- [x] treat "." as null for indexing

**Comment by hextraza** [comment]
Current state of https://github.com/BimberLab/DiscvrLabKeyModules/tree/23.3_fb_lucenePaginatedRawSearch -- fixing the issues listed above, validating functionality and adding integration tests for operations, and fixing some aesthetic concerns.
